### PR TITLE
feat: add helm chart for issuer component

### PR DESCRIPTION
**Pull request by Phil91**
## Description

Add helm chart for issuer component

## Why

To provide a deployment for the issuer component

## Issue

N/A

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/ssi-credential-issuer/blob/main/docs/technical-documentation/dev-process/How%20to%20contribute.md)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added copyright and license headers, footers (for .md files) or files (for images)

### CODE REVIEW

**Comment by Phil91** [comment]
Before merging this PR #18  should be merged

**Review by evegufy — CHANGES_REQUESTED** [review]
could you please remove [SsiCredentialIssuer.Expiry.App.app](https://github.com/eclipse-tractusx/ssi-credential-issuer/tree/feature/helm-charts/src/credentials/SsiCredentialIssuer.Expiry.App.app)  directory? It's removed in #18 but not in this PR

**Comment by Phil91** [comment]
> could you please remove [SsiCredentialIssuer.Expiry.App.app](https://github.com/eclipse-tractusx/ssi-credential-issuer/tree/feature/helm-charts/src/credentials/SsiCredentialIssuer.Expiry.App.app) directory? It's removed in #18 but not in this PR

Removed

**Review by evegufy — APPROVED** [review]
LGTM now once https://github.com/eclipse-tractusx/ssi-credential-issuer/pull/18#pullrequestreview-1947302054 is solved also the helm test and owasp workflow should run successfully

**Pull request merged**
